#!/bin/sh

# params: index lineNumber message
warn() {
    echo "$1:$2:" | perl -p -e "s/$/ warning: Localization: $3/"
}

# params: -
enumFile() {
    if [ -z "$SCRIPT_INPUT_FILE_0" ]
    then
        enumFile=`find "$SRCROOT" -name "Strings.swift"`
    else
        enumFile="$SCRIPT_INPUT_FILE_0"
    fi
}

# params: -
enumKeys() {
    enumKeys=`cat "$enumFile" | egrep -o "case\s.*$" | sed "s/case //g"`
}

# params: -
stringsFiles() {
    IFS=$'\t\n'
    stringsFiles=("`find "$SRCROOT" -name "*.strings" -type f`")
    unset $IFS
}

# params: stringsFile
stringsKeys() {
    stringsKeys=`cat "$1" | egrep -o "^\"\w+\"" | sed "s/\"//g"`
}

# params: pattern file
lineNumber() {
    lineNumber=(`egrep --line-number -o "$1" "$2" | cut -f1 -d:`)
}

# params: stringsFile
findUndefinedStringsKeys() {
    enumFile
    stringsKeys "$1"

    for key in $stringsKeys
    do
        if ! egrep -q "case $key" "$enumFile"
        then
            lineNumber "^\"$key" "$1"
            warn $1 $lineNumber "Key doesn't exist: \"$key\""
        fi
    done
}

# params: stringsFile
findDuplicateStringsKeys() {
    stringsKeys "$1"

    duplicateKeys=`printf '%s\n' ${stringsKeys[@]} | awk '!($0 in seen){seen[$0];next} 1'`
    for key in $duplicateKeys
    do
        lineNumber "^\"$key" "$1"
        warn $1 $lineNumber "Key is duplicated: \"$key\""
    done
}

# params: stringsFile
findUndefinedEnumKeys() {
    enumFile
    enumKeys

    for key in $enumKeys
    do
        if ! egrep -q "^\"$key" "$1"
        then
            warn "$1" 1 "Key is missing: \"$key\""
        fi
    done
}

# params: stringsFile
findUndefinedKeys() {
    echo "> Find undefined keys in: \"$1\""

    findUndefinedStringsKeys "$1"
    findDuplicateStringsKeys "$1"
    findUndefinedEnumKeys "$1"
}

# EXECUTE

stringsFiles
for stringsFile in $stringsFiles
do
    findUndefinedKeys "$stringsFile"
done

